from email.message import EmailMessage
import ssl
import smtplib
from dotenv import load_dotenv
import os
load_dotenv()

# Input your own sender and receivver email
# gmail_password is the password generated by you on the Google Account to get access to the your sender email
email_sender = os.getenv("SENDER_EMAIL")
password = os.getenv("GMAIL_PASSWORD")
email_receiver = os.getenv("RECEIVER_EMAIL")
subject = "Sending Email With Python"
body = "Take a tutorial from freecodecamp, learn it piece by piece, break it down to the core \n Take your time, just learn it step by step."


email = EmailMessage()
email['From'] = email_sender
email['To'] = email_receiver
email['Subject'] = subject
email.set_content(body)

#ecrypt email context with ssl (secure sockets layer)
context = ssl.create_default_context()

# using simple mail transfer protocol to communicate with Gmail server
with smtplib.SMTP_SSL('smtp.gmail.com', 465, context=context) as smtp:
    smtp.login(email_sender, password)
    smtp.sendmail(email_sender, email_receiver, email.as_string())




